/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suruchi;
import java.io.*;

import com.sun.speech.freetts.*;

        
public class chatbot1 extends javax.swing.JFrame {
    String message;
  
    public chatbot1() {
        initComponents();
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        area = new javax.swing.JTextArea();
        javax.swing.JButton b = new javax.swing.JButton();
        speak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        name = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Use Chatbot for Query");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 500, 40);

        area.setEditable(false);
        area.setBackground(new java.awt.Color(0, 0, 0));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setRows(5);
        getContentPane().add(area);
        area.setBounds(20, 110, 570, 590);

        b.setBackground(new java.awt.Color(0, 0, 0));
        b.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Downloads\\send.jpg")); // NOI18N
        b.setText("SEND");
        b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(460, 720, 110, 90);

        speak.setBackground(new java.awt.Color(0, 0, 0));
        speak.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        speak.setForeground(new java.awt.Color(255, 255, 255));
        speak.setText("SPEAK");
        speak.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        speak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                speakMouseReleased(evt);
            }
        });
        speak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakActionPerformed(evt);
            }
        });
        getContentPane().add(speak);
        speak.setBounds(580, 730, 150, 70);

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setColumns(20);
        name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setRows(5);
        jScrollPane1.setViewportView(name);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 710, 420, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Downloads\\bot.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-180, 80, 1300, 760);

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BACK");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(51, 51, 51)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 0, 200, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\Camera Roll\\about.jfif")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -10, 1020, 130);

        setSize(new java.awt.Dimension(1026, 873));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        //area.setText(name.getText());
   
       message=name.getText().toLowerCase();
             // bot("Bot: hello I am here to help you regarding query base don this software");
        //message.concat(s);
        area.append("You : "+name.getText()+"\n");
        name.setText("");
        if(message.contains("hello")||message.contains("hii"))
        {
         
            bot("hyy nice to see you...are you responding");
        }
         else if(message.contains("yes"))
        {
            bot("Ask regarding application available here");
        }
        else if(message.contains("No"))
        {
            bot("Then exit");
        }
        else if(message.contains("thanks")||message.contains("great"))
        {
            bot("yaa!!! tell me who are you and how i can help you");
        }
          else if(message.contains("i am human"))
                  //||message.contains("My name is"+name.getText()+"\n thanks"))
        {
            bot("nice...now tell why are u here");
        }
           else if(message.contains("how are you")){
          
              bot("I am fine..what about you");}
        
        else   if(message.contains("i am good") || message.contains("i am fine")){
         bot("that great");}
       
         else   if(message.contains("having query")||message.contains("having problem")) {
                 //|| message.contains("i am fine")){
         bot("ok...now tell me");}
            else   if(message.contains("what is use of this app")) {
                 //|| message.contains("i am fine")){
         bot("This application consisting various game and utility app.Enjoy!!!");}
          else   if(message.contains("how to play game")||message.contains("how can we play game")){
                 //|| message.contains("i am fine")){
         bot("just double click on particular game icon and a game starting window will appear ...");}
          else   if(message.contains("how to use notepad")) {
                 //|| message.contains("i am fine")){
         bot("This texteditor works same as normally texteditor do");}
          else   if(message.contains("rule of wining tictactoe game")) {
                 //|| message.contains("i am fine")){
         bot("user wins when X or O matches horizontally/vertically/diagonally");}
          else   if(message.contains("what currency-convertor do?")) {
                 //|| message.contains("i am fine")){
         bot("it just converting money value from one currency to another");}
        else
          {
              bot("sorry!!! i can't understand");
          }
        
          //  else if(message.contains("I am upset"))
          //||message.contains("I have a query"))
          //|| message.contains("i have a problem"))
          
          // bot("so sad!!! tell me your query");
          //else
          //{
          //    bot("can't understand");
          //}
          //String s="";
          
          // message.concat(s);
          //Socket sock=new Socket();
          
          // else if(message.contains("I am also fine")){
          //bot("Wow, that's great!!!");
          //}

        
       
    }//GEN-LAST:event_bActionPerformed
private static final String VOICENAME="kevin16";
    private void speakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakActionPerformed
      Voice voice;
     VoiceManager vm=VoiceManager.getInstance();
    voice=vm.getVoice(VOICENAME);
    voice.allocate();
    //  voice.speak(area.getText());
     
       
      try{
          voice.speak(area.getText());
      }
      catch(Exception e)
              {
                  
              }
    }//GEN-LAST:event_speakActionPerformed

    private void speakMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speakMouseReleased
      
       // Voice voice;
       // System.setProperty("mbrola.base","mbrola");
       //VoiceManager vm=VoiceManager.getInstance();
       //voice=vm.getVoice(VOICENAME);
        //voice.allocate();
        //voice.speak(area.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_speakMouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new MENU_DESIGN().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
   // public static void bot(String message)
	
	//	area.append("Bot : "+message+"\n");
	
    
    /**
     * @param args the command line arguments
     */
    public  void bot(String message)
	{
          // area.append("Bot:"+"hello");
		area.append("Bot : "+message+"\n");
	}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatbot1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatbot1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatbot1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatbot1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatbot1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea name;
    private javax.swing.JButton speak;
    // End of variables declaration//GEN-END:variables

    //To change body of generated methods, choose Tools | Templates.
    
}
