package suruchi;


import java.sql.Connection;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Loading_tictactoe1 extends javax.swing.JFrame implements Runnable {
   
 Connection conn;
 int s=0;
 Thread th;

    public Loading_tictactoe1() {
        super("Loading");    
     //heading
     initComponents();
        th=new Thread((Runnable)this);   
    }
    public void setUpLoading()
    {
      setVisible(false);
      th.start();
    }
 @Override
    public void run()
    {
    try
    {
        for(int i=1;i<=200;i++)
        {
            s=s+1;
            int m=bar.getMaximum();
            int n=bar.getValue();
            if(n<m)
            {
        
                bar.setValue(bar.getValue()+1);
            }
            else
            {
               i= 201;
               setVisible(false);
               Java_tic_tac_toe1 ob=new Java_tic_tac_toe1();
               ob.setVisible(true);
            }
            Thread.sleep(50);
        }
        
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        bar.setBackground(new java.awt.Color(0, 0, 0));
        bar.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        bar.setForeground(new java.awt.Color(0, 0, 0));
        bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 5));
        bar.setStringPainted(true);
        getContentPane().add(bar);
        bar.setBounds(60, 290, 840, 90);

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loading..................................");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 190, 510, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/toe.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 980, 680);

        setSize(new java.awt.Dimension(977, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading_tictactoe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading_tictactoe1.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading_tictactoe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading_tictactoe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
//
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading_tictactoe1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
